# Generated by Django 4.1.5 on 2023-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categeroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=5000)),
                ('Description', models.TextField(max_length=500)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-hidden  ')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
