# Generated by Django 4.1.5 on 2023-03-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('product_img', models.CharField(max_length=2000)),
                ('Quantity', models.IntegerField()),
                ('original_price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('categeroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booksapp.categeroy')),
            ],
        ),
    ]
