# Generated by Django 4.1.5 on 2023-03-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='BooksProduct',
        ),
    ]
