# Generated by Django 4.1.5 on 2023-03-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0003_rename_product_booksproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksproduct',
            name='latest',
            field=models.BooleanField(default=False, help_text='0-default,1-Trending'),
        ),
    ]
