# Generated by Django 4.1.7 on 2023-03-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksproduct',
            name='product_img',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='categeroy',
            name='Image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
