# Generated by Django 4.1.7 on 2023-03-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0007_orders_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_qty',
        ),
    ]
