# Generated by Django 4.1.7 on 2023-03-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0009_cart_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grand_total', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booksapp.cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
