# Generated by Django 4.1.7 on 2023-03-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0010_finalorder_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='Qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
