# Generated by Django 4.1.7 on 2023-03-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booksapp', '0011_finalorder_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='placeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.IntegerField()),
                ('GrandTotal', models.IntegerField()),
                ('ordered_on', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, help_text='0-show ,1-hidden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
