# Generated by Django 4.1.7 on 2023-03-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0012_placeorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='placeorder',
        ),
    ]
