# Generated by Django 4.1.5 on 2025-01-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0015_remove_finalorder_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('Subject', models.CharField(max_length=40)),
                ('Message', models.TextField()),
            ],
        ),
    ]
