# Generated by Django 4.1.5 on 2023-02-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_hello'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello',
        ),
        migrations.DeleteModel(
            name='Imagedisplaynew',
        ),
    ]
