# Generated by Django 4.1.5 on 2023-03-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_delete_hello_delete_imagedisplaynew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiction',
            name='img',
            field=models.CharField(max_length=600),
        ),
    ]
