# Generated by Django 4.1.5 on 2023-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_fiction_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiction',
            name='img',
            field=models.CharField(max_length=2000),
        ),
    ]
