# Generated by Django 4.1.5 on 2023-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_fiction_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=500)),
                ('pages', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.CharField(max_length=3000)),
            ],
        ),
    ]
