# Generated by Django 4.1.5 on 2023-03-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='Author',
        ),
    ]
