# Generated by Django 4.1.5 on 2023-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_books_cover_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('new_image', models.ImageField(blank=True, null=True, upload_to='static/imgfolder/')),
            ],
        ),
    ]
