# Generated by Django 4.1.5 on 2023-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='new_image',
            field=models.ImageField(default='temp.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
