# Generated by Django 4.1.5 on 2023-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_alter_bookimage_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover_page',
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='new_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
