# Generated by Django 4.1.7 on 2023-03-15 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_remove_books_cover_page_alter_bookimage_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
