# Generated by Django 5.2 on 2026-01-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booksapp', '0003_recorddetails_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordDetails',
        ),
    ]
